# Generated by Django 5.2.13 on 2026-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('job_description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
